-- AUTO_INCREMENT

CREATE TABLE TAB_IDENTITY (ID INT AUTO_INCREMENT, DESCRITOR VARCHAR(20), PRIMARY KEY(ID));

INSERT INTO TAB_IDENTITY (DESCRITOR) VALUES ('CLIENTE 1');
INSERT INTO TAB_IDENTITY (DESCRITOR) VALUES ('CLIENTE 2');
INSERT INTO TAB_IDENTITY (DESCRITOR) VALUES ('CLIENTE 3');

-- SAME AS ABOVE
INSERT INTO TAB_IDENTITY (ID, DESCRITOR) VALUES (NULL, 'CLIENTE 4');

DELETE FROM TAB_IDENTITY WHERE ID = 2;

INSERT INTO TAB_IDENTITY (DESCRITOR) VALUES ('CLIENTE 5');

DELETE FROM TAB_IDENTITY WHERE ID = 5;

INSERT INTO TAB_IDENTITY (DESCRITOR) VALUES ('CLIENTE 6');

-- JUMPS UP THE BOTTON OF AUTOINCREMENT
INSERT INTO TAB_IDENTITY (ID, DESCRITOR) VALUES (100, 'CLIENTE 110');

INSERT INTO TAB_IDENTITY (DESCRITOR) VALUES ('CLIENTE 7');

INSERT INTO TAB_IDENTITY (ID, DESCRITOR) VALUES (5, 'CLIENTE 115');

INSERT INTO TAB_IDENTITY (DESCRITOR) VALUES ( 'CLIENTE 125');

SELECT * FROM TAB_IDENTITY;
