-- Criação de tabela com PK

USE vendas_sucos;

create table PRODUTOS
(	
	CODIGO VARCHAR(10) NOT NULL,
    DESCRITOR VARCHAR(100) NULL,
    SABOR VARCHAR(50) NULL,
    TAMANHO VARCHAR(50) NULL,
    EMBALHAGEM VARCHAR(50) NULL,
    PRECO_LISTA FLOAT NULL,
    PRIMARY KEY(CODIGO));

CREATE TABLE VENDEDORES
(   
    MATRICULA VARCHAR(5) NOT NULL,
    NOME VARCHAR(100) NULL,
    BAIRRO VARCHAR (50),
    COMISSAO FLOAT NULL, 
    DATA_ADMISSAO DATE NULL
    FERIAS BIT(1) NULL,
    PRIMARY KEY (MATRICULA));