-- Setting defaults for fields
CREATE TABLE TAB_PADRAO
(ID INT AUTO_INCREMENT,
DESCRITOR VARCHAR(20), 
ENDERECO VARCHAR (100) NULL, -- IF NOT SET IT WILL BE AUTOMATICALLY SET AS NULL
CIDADE VARCHAR(50) DEFAULT 'Rio de Janeiro', -- IF NOT SET IT WILL BE AUTOMATICALLY SET WITH THE DEFAULT VALUE
DATA_CRIACAO timestamp DEFAULT CURRENT_TIMESTAMP(),
primary key (ID));

INSERT INTO TAB_PADRAO (DESCRITOR, ENDERECO, CIDADE, DATA_CRIACAO)
VALUES ('CLIENTE X', 'RUA PROJETADA A', 'SAO PAULO', '2019-01-01');

SELECT * FROM TAB_PADRAO;


INSERT INTO TAB_PADRAO (DESCRITOR)
VALUES ('CLIENTE Y');

INSERT INTO TAB_PADRAO (ENDERECO, CIDADE, DATA_CRIACAO)
VALUES ('RUA PROJETADA A', 'SAO PAULO', '2019-01-01');
