-- Agrupando os resultados

SELECT * FROM tabela_de_clientes;

SELECT ESTADO, LIMITE_DE_CREDITO FROM tabela_de_clientes;

SELECT ESTADO, SUM(LIMITE_DE_CREDITO) AS LIMITE_TOTAL FROM tabela_de_clientes GROUP BY ESTADO;

SELECT EMBALAGEM, PRECO_DE_LISTA FROM tabela_de_produtos;

SELECT EMBALAGEM, MAX(PRECO_DE_LISTA) AS MAIOR_PREÇO FROM tabela_de_produtos group by EMBALAGEM;

SELECT EMBALAGEM, COUNT(*) AS CONTAGEM FROM tabela_de_produtos group by EMBALAGEM;

SELECT EMBALAGEM, COUNT(*) AS CONTAGEM FROM tabela_de_produtos group by EMBALAGEM;

SELECT BAIRRO, SUM(LIMITE_DE_CREDITO) AS LIMITE FROM tabela_de_clientes group by BAIRRO;

SELECT BAIRRO, SUM(LIMITE_DE_CREDITO) AS LIMITE FROM tabela_de_clientes WHERE 
CIDADE = 'RIO DE JANEIRO' group by BAIRRO;

SELECT ESTADO, BAIRRO, SUM(LIMITE_DE_CREDITO) AS LIMITE FROM tabela_de_clientes group by ESTADO, BAIRRO;

SELECT ESTADO, BAIRRO, SUM(LIMITE_DE_CREDITO) AS LIMITE FROM 
 tabela_de_clientes group by ESTADO, BAIRRO order by ESTADO;
 
 SELECT COUNT(*) AS CONTAGEM FROM itens_notas_fiscais 
 WHERE CODIGO_DO_PRODUTO= 1101035 AND QUANTIDADE = 99 GROUP by CODIGO_DO_PRODUTO;