-- Table creation with FK

use venda_sucos;

CREATE TABLE TABELA_DE_VENDAS
(NUMERO VARCHAR(5) NOT NULL,
DATA_VENDA DATE NULL,
CPF VARCHAR(11) NOT NULL, 
MATRICULA VARCHAR(5) NOT NULL,
IMPOSTO FLOAT NULL,
PRIMARY KEY (NUMERO));

ALTER TABLE TABELA_DE_VENDAS ADD constraint FK_CLIENTE
FOREIGN KEY(CPF) REFERENCES CLIENTES(CPF);

ALTER TABLE TABELA_DE_VENDAS ADD constraint FK_VENDEDORES
FOREIGN KEY(MATRICULA) REFERENCES VENDEDORES(MATRICULA);

/*
Crie, por linha de comando, a chave estrangeira ligando a tabela de PRODUTOS com a tabela de
ITENS_NOTAS através do campo CODIGO e outra ligação entre a tabela NOTAS e ITENS_NOTAS 
através do campo NUMERO. */


ALTER TABLE ITENS_NOTAS ADD constraint FK_PRODUTOS
FOREIGN KEY(CODIGO) REFERENCES PRODUTOS(CODIGO);

ALTER TABLE ITENS_NOTAS ADD CONSTRAINT FK_NOTAS
FOREIGN KEY (NUMERO)
REFERENCES NOTAS (NUMERO);