CREATE TABLE tbClientes(
	CPF VARCHAR(11),
    NOME VARCHAR(100),
    ENDERECO1 VARCHAR(150),
    ENDERECO2 VARCHAR(150),
    BAIRRO VARCHAR(50),
    CIDADE VARCHAR(50),
    ESTADO VARCHAR(50),
    CEP VARCHAR(8),
    IDADE SMALLINT,
    SEXO VARCHAR(1),
    LIMITE_CREDITO FLOAT,
    VOLUME_COMPRA FLOAT,
    PRIMEIRA_COMPRA BIT(1)
	);
    
    CREATE TABLE TABELA_DE_VENDEDORES (
    MATRICULA varchar(5), 
    NOME varchar(100), 
    PERCENTUAL_COMISSAO float
);